services:

  mysql:
    image: mysql:8.0
    container_name: mdd-mysql
    restart: unless-stopped
    ports:
      - "3309:3306"
    env_file:
      - .env-mysql
    volumes:
      - mdd_mysql_data:/var/lib/mysql
    networks:
      - mdd_network

volumes:
  mdd_mysql_data:


networks:
  mdd_network:
